language: node_js
before_script:
  - npm install -g gatsby-cli
git:
  depth: false
  quiet: true
node_js:
  - "13"
deploy:
  - provider: script
    script: yarn install && yarn run deploy
    skip_cleanup: true
    on:
      branch: develop